---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  namespace: app1
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 438748127802.dkr.ecr.us-west-2.amazonaws.com/demo-nginx:latest
        ports:
        - containerPort: 80
